[package]
name = "chriscerie/roact-spring-story"
description = "Stories for react-spring"
version = "0.0.6"
license = "MIT"
authors = ["chriscerie"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
Roact = "roblox/roact@^1"
Hooks = "kampfkarren/roact-hooks@^0.3"
Promise = "evaera/promise@^3.2"